############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
#  port: 8088
  port: 8080
  servlet:
    context-path: /superhero
  tomcat:
    uri-encoding: UTF-8
    
############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                             ## 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource              # 数据源 HikariCP
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动
    url: jdbc:mysql://192.168.1.3:3306/next-superhero-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root               # 本地数据库 
    hikari:                           
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 15           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DatebookHikariCP     # 连接池名字
      max-lifetime: 28740000          # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      connection-test-query: SELECT 1
  redis:                  # Redis 的配置
    database: 0           # Redis 的数据库下标（索引，默认为0）
    host: 192.168.1.61    # 本地Redis服务的内网IP（分布式环境，必须保证内网互通，并且在同一个网段）
    port: 6379            # 端口
    password: next        # 密码
  servlet:
    multipart:
      max-file-size: 10485760      # 文件上传配置 限制10m
      max-request-size: 10485760   # 文件上传配置 限制10m
  rabbitmq: 
    host: 192.168.1.66
    port: 5672
    username: admin
    password: admin
    virtual-host: /superhero 
      
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.next.pojo                     # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml                  # mapper映射文件
   
############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.next.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql